### PR TITLE
COO-261: Support tolerations and nodeselector in Monitoringstack

### PR DESCRIPTION
**Pull request by PaulFarver**
Add support for tolerations and nodeselectors in the monitoringstack CRD.

### CODE REVIEW

**Comment by simonpasquier** [comment]
Thanks for the PR! Commit messages need to start with `feat: ...` or `chore: ...`. There's also an issue with the generated code not being up-to-date apparently.

**Comment by PaulFarver** [comment]
@simonpasquier thanks for looking at this :)

I've updated the commit messages, but I'm unsure what to do about the generated code. When I run `make generate` the output is what's in the current PR

**Comment by simonpasquier** [comment]
Yeah, the code generation can be tricky sometimes. Can you try running ` make --always-make generate bundle`? Otherwise I can probably push the required changes to your branch.

**Comment by simonpasquier** [comment]
You'd need also to amend the commit messages to remove the upper-case after the `:` .

**Comment by PaulFarver** [comment]
Yeah. It should be updated now

**Comment by simonpasquier** [comment]
/lgtm
/approve

Thanks!

**Comment by simonpasquier** [comment]
I pushed onto your branch the updated version of `bundle/manifests/observability-operator.clusterserviceversion.yaml`.

**Pull request merged**
