### PR TITLE
feat: bump Prometheus operator to v0.68.0

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by jan--f** [comment]
I think we want `s/v0.68.0-rhobs1/v0.68.0-rhobs2/` everywhere?

**Comment by danielmellado** [comment]
probably, as we skipped rhobs1 as per the merge commit and the automation

**Comment by simonpasquier** [comment]
In fact I messed up with the `rhobs-rel-0.68.0-rhobs2` branch and there's no `v0.68.0-rhobs2` of the obo-prometheus-operator image (see https://quay.io/repository/rhobs/obo-prometheus-operator?tab=tags). There's only a `v0.68.0-rhobs1` tag which is built from https://github.com/rhobs/obo-prometheus-operator/commit/a15e510b7cf2a728964f6cd0aa963f47167778a7.

**Comment by jan--f** [comment]
Alright, as long as the sha\s line up :)
/lgtm

**Pull request merged**
