### PR TITLE
chore: use fmt.Sprintf for YAML generation

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by jan--f** [comment]
Nice, thanks!
/lgtm

**Comment by simonpasquier** [comment]
@jan--f the CI tests are broken by my change for now ;)

**Comment by jan--f** [comment]
/lgtm
/hold
not sure if this is supposed to go into `0.4.2`. Feel free to unhold if so.

**Comment by simonpasquier** [comment]
>  not sure if this is supposed to go into 0.4.2. Feel free to unhold if so.

No it can definitely wait after.

**Pull request merged**
