### PR TITLE
fix: bump controller-gen version

### PR DESCRIPTION
**Pull request by tremes**
Update controller-gen tool version to work with go 1.22

### CODE REVIEW

**Comment by simonpasquier** [comment]
I have also https://github.com/rhobs/observability-operator/pull/455 in progress.

**Review by frzifus — APPROVED** [review]

**Comment by frzifus** [comment]
I am fine with either one of them. ^^

**Comment by tremes** [comment]
@simonpasquier ahh OK sorry. So I think I can close this one.

**Comment by simonpasquier** [comment]
no problem!

**Pull request closed without merging**
