### PR TITLE
feat: restrict UIPlugin CRD names to allow a single instance per type

### PR DESCRIPTION
**Pull request by jgbernalp**
[OU-402](https://issues.redhat.com/browse/OU-402)
[COO-164](https://issues.redhat.com/browse/COO-164)

This PR adds a pattern restriction for the UIPlugin name so only a single instance of a specific plugin is allowed

### CODE REVIEW

**Comment by jan--f** [comment]
/lgtm

Nice! We'll have to chat about OCP specific integration tests soon.

**Comment by simonpasquier** [comment]
AFAIU you can still create conflicting objects if you mess up the names and the types, right? For instance:

````
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: ui-dashboards
spec:
  type: Dashboards
---
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: ui-logging
spec:
  type: Dashboards
````

I don't think that it's possible to validate this case with OpenAPI but we might want the operator to stop reconciliation when it detects the issue?

**Comment by jan--f** [comment]
Ahh I think I might have been (or still am) confused what needs to be done. So there can always only be a single `dashboard` UI plugin? An for logging a new type is added, going by #477?

In that case can we not tie the name to the type? Something like
```
// +kubebuilder:validation:XValidation:rule="self.name == self.spec.type",message="Name is invalid"
```

**Comment by simonpasquier** [comment]
@jan--f this would be neat if it works indeed.

**Comment by jgbernalp** [comment]
Will do some tests based on @jan--f suggestion and update the PR

**Comment by xperimental** [comment]
Just a nitpick, but I think I would get rid of the `ui-` prefix for the names. First it mirrors the name of the resource type (`UIPlugin`) and it also currently causes the deployments to be named `observability-ui-ui-*` (which could be changed in the operator though).

**Comment by jgbernalp** [comment]
/hold

@csibbitt please check if changes are needed for STF

**Review by simonpasquier — COMMENTED** [review]
/lgtm
/hold

:+1:

**Comment by csibbitt** [comment]
> /hold
> 
> @csibbitt please check if changes are needed for STF

STF does not use the UIPlugin, but Telemetry Operator does. I'll take care of this ASAP on  OSPRH-7600

**Comment by jgbernalp** [comment]
since the change for the telemetry operator was merged https://github.com/openstack-k8s-operators/telemetry-operator/pull/406, we can proceed with this.

/unhold

**Pull request merged**
