### PR TITLE
chore: add suggested namespace to bundle

### PR DESCRIPTION
**Pull request by jan--f**
Fixes: [COO-32](https://issues.redhat.com//browse/COO-32)

### CODE REVIEW

**Review by marioferh — COMMENTED** [review]
/lgtm

**Comment by simonpasquier** [comment]
/lgtm

will we customize this downstream with an `openshift-` prefix?

**Comment by simonpasquier** [comment]
replying to myself, we need the openshift- prefix to display the "enable cluster monitoring" checkbox during install.

**Comment by jan--f** [comment]
fixed in https://github.com/rhobs/konflux-coo/pull/186

**Pull request merged**
