### PR TITLE
chore: update operator-sdk v1.31.0

### PR DESCRIPTION
**Pull request by marioferh**
Operator-sdk needs this update: https://github.com/operator-framework/operator-sdk/pull/6408 in order to fix this: 
https://github.com/rhobs/observability-operator/blob/b6b11bb4f5e5a53041e555169abd71d7c1543ec4/deploy/dependencies/kustomization.yaml#L6-L21

### CODE REVIEW

**Review by jan--f — DISMISSED** [review]
The commit linter actually looks at the commit message, not the PR message. I'd recommend squashin bot into one commit and adding `chore: ` to the title.

The generate job looks like it needs a change after updating `operator-sdk`. The `created-at` annotation makes this test fail, since it gets regenerated. Maybe we can prevent operator-sdk to add that?

**Comment by danielmellado** [comment]
Same comment as @jan--f , please do a squash of both commits and fix violations. I'd recommend triggering the linter locally before pushing, thanks!

**Review by danielmellado — CHANGES_REQUESTED** [review]
Small nit already explained

**Comment by danielmellado** [comment]
> The commit linter actually looks at the commit message, not the PR message. I'd recommend squashin bot into one commit and adding `chore: ` to the title.
> 
> The generate job looks like it needs a change after updating `operator-sdk`. The `created-at` annotation makes this test fail, since it gets regenerated. Maybe we can prevent operator-sdk to add that?

https://github.com/operator-framework/operator-sdk/issues/6285 Seems related to this, we'll probably need to actively ignore that.

**Comment by jan--f** [comment]
https://github.com/operator-framework/operator-sdk/issues/6285#issuecomment-1532150678 might be solution.

**Comment by marioferh** [comment]
> [operator-framework/operator-sdk#6285 (comment)](https://github.com/operator-framework/operator-sdk/issues/6285#issuecomment-1532150678) might be solution.

thanks, done

**Comment by jan--f** [comment]
/lgtm
Thanks!

**Review by danielmellado — APPROVED** [review]
/lgtm

**Pull request merged**
