### PR TITLE
COO-485: feat: deploy PrometheusRule resource

### PR DESCRIPTION
**Pull request by simonpasquier**
This change deploys a PrometheusRule resource with one alerting rule firing when one controller hits more than 10% of failed reconciliations in the last 5 minutes for more than 15 minutes.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/hold
we need to clean up the legacy PrometheusRule resources.

**Comment by jan--f** [comment]
oh nice, thanks! Unhold at will
/lgtm

**Pull request merged**
