### PR TITLE
feat: bump Prometheus operator to v0.74.0

### PR DESCRIPTION
**Pull request by marioferh**

### CODE REVIEW

**Review by simonpasquier — APPROVED** [review]
/lgtm

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by simonpasquier** [comment]
/hold
shellcheck is blocking

**Comment by marioferh** [comment]
> /hold shellcheck is blocking

is no shellheck, is this test after the enableGate type change:

        +++ expected
          map[string]any{
          	... // 2 identical entries
          	"f:alerting":                    map[string]any{"f:alertmanagers": map[string]any{}},
          	"f:arbitraryFSAccessThroughSMs": map[string]any{},
        - 	"f:enableFeatures":              map[string]any{`v:"otlp-write-receiver"`: map[string]any{}},
        + 	"f:enableFeatures":              map[string]any{},
          	"f:enableRemoteWriteReceiver":   map[string]any{},
          	"f:externalLabels":              map[string]any{"f:key": map[string]any{}},
          	... // 24 identical entries
          }
        

let me fix it

**Comment by marioferh** [comment]
> "f:enableFeatures":              map[string]any{`v:"otlp-write-receiver"`: map[string]any{}},

in fact before the expected was: 
"f:enableFeatures":              map[string]any{},

and the test passed... should be:

"f:enableFeatures":              map[string]any{`v:"otlp-write-receiver"`: map[string]any{}},

as right now..

**Comment by simonpasquier** [comment]
> there was a bug before?

no bug but an upstream change that broke the test :)

https://github.com/prometheus-operator/prometheus-operator/commit/3e0d0f86f2

/lgtm

**Pull request merged**
