### PR TITLE
chore(release): 0.3.5

### PR DESCRIPTION
**Pull request by marioferh**

### CODE REVIEW

**Comment by marioferh** [comment]
@simonpasquier

**Comment by simonpasquier** [comment]
hmm no https://github.com/rhobs/observability-operator/commit/8c4e1a4a3e06a47ccbb97b74cc47b127d10d78e8?

**Comment by marioferh** [comment]
> hmm no [8c4e1a4](https://github.com/rhobs/observability-operator/commit/8c4e1a4a3e06a47ccbb97b74cc47b127d10d78e8)?

Now is in, maybe we did it at the same time and the PR was not included yet...

**Review by simonpasquier — APPROVED** [review]
/lgtm

**Pull request merged**
