### PR TITLE
MON-3407: chore(release): 0.0.26

### PR DESCRIPTION
**Pull request by jan--f**

### CODE REVIEW

**Comment by simonpasquier** [comment]
The pod failed to be spawned with `Back-off pulling image "observability-operator:0.0.26"`.

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/rhobs_observability-operator/368/pull-ci-rhobs-observability-operator-main-observability-operator-e2e/1712094625650446336/artifacts/observability-operator-e2e/gather-must-gather/artifacts/event-filter.html

**Comment by simonpasquier** [comment]
The previous release (https://github.com/rhobs/observability-operator/pull/325) didn't have the prow jobs. This is a chiken-and-egg problem :-/

**Comment by jan--f** [comment]
I changed the required tests earlier today to not require the prow e2e tests for now, but it seems like prow reversed that. Overriding the checks for now.

**Pull request merged**
