### PR TITLE
fix: update url link to rhobs-handbook.netlify.app

### LINKED ISSUE #287: Link to https://observability-operator.rhobs.io/ which doesn't exist
I've found https://github.com/rhobs/observability-operator/blob/82fc388b64fb39d32560687c7253df95e8d9fefe/deploy/olm/bases/observability-operator.clusterserviceversion.yaml#L43 and https://github.com/rhobs/observability-operator/blob/82fc388b64fb39d32560687c7253df95e8d9fefe/bundle/manifests/observability-operator.clusterserviceversion.yaml#L582 which redirects to a non-existing domain.

It's probably better to link to https://rhobs-handbook.netlify.app/ for now.

### PR DESCRIPTION
**Pull request by slashpai**
Fixes #287

### CODE REVIEW

**Review by simonpasquier — APPROVED** [review]
let's hear from @jan--f and @sthaha

**Comment by sthaha** [comment]
Thanks @slashpai . I am okay with it. 
Just a thought - https://rhobs-handbook.netlify.app/products/observability-operator so that this can be created and left empty for now.

**Comment by slashpai** [comment]
> Thanks @slashpai . I am okay with it. Just a thought - https://rhobs-handbook.netlify.app/products/observability-operator so that this can be created and left empty for now.

ya that looks good to me, shall we create empty page now in handbook for now?

**Comment by simonpasquier** [comment]
@slashpai yes let's create a minimal page about ObO in the rhobs/handbook repo first.

**Comment by slashpai** [comment]
https://deploy-preview-56--rhobs-handbook.netlify.app/products/observabilityoperator/

**Comment by sthaha** [comment]
> https://deploy-preview-56--rhobs-handbook.netlify.app/products/observabilityoperator/

Thanks a lot 🤗 
sorry if this sounds pedantic. Is it possible to have `products/observability-operator` to match the gh repo name? and for better readability?

**Comment by slashpai** [comment]
> > https://deploy-preview-56--rhobs-handbook.netlify.app/products/observabilityoperator/
> 
> Thanks a lot 🤗 sorry if this sounds pedantic. Is it possible to have `products/observability-operator` to match the gh repo name? and for better readability?
> 
> Update: This is possible by renaming ObservabiltyOperator to `Observabilty-Operator`

https://deploy-preview-56--rhobs-handbook.netlify.app/products/observability-operator/ good ? :)

**Review by sthaha — APPROVED** [review]

**Pull request merged**
