### PR TITLE
COO-525: fix the creation of the operator's ServiceMonitor resource when not running in the default namespace

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by simonpasquier** [comment]
/hold

It fails because the operator can't create the service monitor. From https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/rhobs_observability-operator/620/pull-ci-rhobs-observability-operator-main-observability-operator-e2e/1856369104441577472/artifacts/observability-operator-e2e/gather-extra/artifacts/pods/coo_observability-operator-858d7cdb76-ns2gn_operator.log

````
2024-11-12T16:49:27Z	ERROR	Reconciler error	{"controller": "observability-operator", "controllerGroup": "", "controllerKind": "Service", "Service": {"name":"observability-operator","namespace":"coo"}, "namespace": "coo", "name": "observability-operator", "reconcileID": "5dc70ade-9329-4444-91ee-5af5d348d591", "error": "coo/observability-operator (monitoring.coreos.com/v1, Kind=ServiceMonitor): updater failed to patch: servicemonitors.monitoring.coreos.com \"observability-operator\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
````

cc @jan--f

**Comment by simonpasquier** [comment]
cc @lihongyan1

**Comment by jan--f** [comment]
/lgtm
Thanks a lot!

**Comment by simonpasquier** [comment]
/hold cancel
It should be good now

**Pull request merged**
